spring:
  application:
    name: telemed-ia-identity-and-access-api

  profiles:
    default: dev

server:
  port: ${PORT:8081}

management:
  server:
    port: ${MANAGEMENT_PORT:9081}

  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true

security:
  jwt:
    issuer: ${JWT_ISSUER:telemed-ia-identity-and-access}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:PT15M}
    secret-base64: ${JWT_SECRET_BASE64}