spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/telemed_identity}
    username: ${DB_USERNAME:telemed_identity}
    password: ${DB_PASSWORD:telemed_identity_dev}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    com.telemed.identityaccess: INFO